<a href="https://colab.research.google.com/github/Goose-kr/Data_analysis/blob/master/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22NumPy_%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D0%BD%D0%BE%D0%BB%D1%8C_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать их работу. Для каждой функции добавить комментарий.

In [19]:
import numpy as np

# Это функция питона  используемая, чтобы вернуть тип переданного параметра
a = np.array([[1,2,3],[4,5,6]])
print(type(a))

# Эта функция создаст массив numpy с заданным количесетвом измерений, где каждый элемент равен нулю 
b = np.zeros((4,4))
print(b)

# Все тоже самое, что сверху, но теперь массив единиц 
c = np.ones((3,3))
print(c)

# Функция создаст массив, со случайным содержимым (оно зависит от памяти)
d = np.empty((5,5))
print (d)

# Функция создаст массив, элементы которого лежат в диапазоне хначений между start, stop, с шагом step 
e = np.linspace(1,100,10)
print (e)

# Функция используется для создания массива, элементы которого лежат в диапазоне значений от start до stop, а num_of_elements - размер массива. Все элементы в пределах логарифмической шкалы, то есть представляют собой логарифмы соответствующих элементов 
f = np.logspace(5, 25,5)
print(f)

# Вернет синус параметра 
print (np.sin(f))

# Функция используется для изменения количества измерений массива numpy. От количества аргументов в reshare зависит, сколько измерений будет в массиве numpy.
g = np.arange(9)
k = np.reshape(g, (3,3)) 
print(k)

# Эта функция возвращает массив с заданным количеством измерений, где каждый элемент генерируется случайным образом.
h = np.random.random((2,2))
print (h)

# Функция вернет ndarray с экспоненциальной величиной каждого элемента.
i = np.exp([10])
print (i)

# Эта функция вернет ndarray с квадратным корнем каждого элемента.
j = np.sqrt([12,34,12])
print(j)

<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4.67281549e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[1.e+05 1.e+10 1.e+15 1.e+20 1.e+25]
[ 0.0357488  -0.48750603  0.85827279 -0.64525129 -0.3052578 ]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0.41340936 0.05765984]
 [0.44255448 0.99823498]]
[22026.46579481]
[3.46410162 5.83095189 3.46410162]


Сгенерировать 3-х мерный массив, где 0-я ось - id группы товаров, 1-я ось - id магазина, 2-я ось - день месяца, в которой осуществлялась продажа 


In [23]:
import numpy as np
from numpy import random

a = np.array([[[0 for i in range(5)]for j in range(12)] for k in range(23)])
print(a)
print (a.ndim)

#b = np.array([[random(5)], [random(10)], [random(40)]])
a.insert(1,1)
print (a)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  ...
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  ...
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  ...
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 ...

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  ...
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  ...
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  ...
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
3


AttributeError: ignored